experiments:
  registration_copy:
    variants:
      - Food delivery with a purpose
      - green
      - blue
    winner: Food delivery with a purpose

exclude:
  bots: true
  ips:
    - 127.0.0.1
    - 10.0.0.0/8